{{- if .Values.flink.jobs.embedding.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "slo-scout.fullname" . }}-embedding-job
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: embedding-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "20"
spec:
  template:
    metadata:
      labels:
        {{- include "slo-scout.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: embedding-job
    spec:
      serviceAccountName: {{ include "slo-scout.serviceAccountName" . }}
      restartPolicy: OnFailure
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: embedding-job
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.flink.jobs.embedding.image.repository }}:{{ .Values.flink.jobs.embedding.image.tag }}"
        imagePullPolicy: {{ .Values.flink.jobs.embedding.image.pullPolicy }}
        args:
        - run
        - -d
        - -p
        - "{{ .Values.flink.jobs.embedding.config.parallelism }}"
        - /opt/flink/jobs/embedding-pipeline-job.jar
        env:
        {{- include "slo-scout.commonEnv" . | nindent 8 }}
        - name: FLINK_JOBMANAGER_ADDRESS
          value: {{ include "slo-scout.fullname" . }}-flink-jobmanager:6123
        - name: CHECKPOINT_INTERVAL
          value: {{ .Values.flink.jobs.embedding.config.checkpointInterval | quote }}
        - name: BATCH_SIZE
          value: {{ .Values.flink.jobs.embedding.config.batchSize | quote }}
        {{- with .Values.flink.jobs.embedding.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 9999
          allowPrivilegeEscalation: false
{{- end }}
