apiVersion: apps/v1
kind: Deployment
metadata:
  name: otlp-collector
  namespace: slo-scout
  labels:
    app: otlp-collector
    component: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otlp-collector
  template:
    metadata:
      labels:
        app: otlp-collector
    spec:
      containers:
      - name: otlp-collector
        image: slo-scout/otlp-collector:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: slo-scout-config
              key: KAFKA_BOOTSTRAP_SERVERS
        ports:
        - containerPort: 4317
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: health
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: otlp-collector
  namespace: slo-scout
spec:
  selector:
    app: otlp-collector
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: health
    port: 8080
    targetPort: 8080
