{{- if .Values.customKafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slo-scout.fullname" . }}-kafka
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  ports:
  - port: 9092
    name: client
    targetPort: 9092
  selector:
    {{- include "slo-scout.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slo-scout.fullname" . }}-kafka
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: {{ .Values.customKafka.replicaCount }}
  selector:
    matchLabels:
      {{- include "slo-scout.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        {{- include "slo-scout.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.customKafka.image }}
        ports:
        - containerPort: 9092
          name: client
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ include "slo-scout.fullname" . }}-zookeeper.{{ include "slo-scout.namespace" . }}.svc.cluster.local:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://{{ include "slo-scout.fullname" . }}-kafka.{{ include "slo-scout.namespace" . }}.svc.cluster.local:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        resources:
          {{- toYaml .Values.customKafka.resources | nindent 10 }}
{{- end }}
