apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-scout-config
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ include "slo-scout.kafkaBootstrapServers" . | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  LOG_LEVEL: {{ index .Values.configMaps "slo-scout-config" "LOG_LEVEL" | default "info" | quote }}

  # Database configuration
  DB_HOST: {{ include "slo-scout.databaseHost" . | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.timescaledb.auth.database | default "slo_scout" | quote }}
  DB_USER: {{ .Values.timescaledb.auth.username | default "slo_scout" | quote }}

  # Storage configuration
  S3_ENDPOINT: {{ include "slo-scout.minioEndpoint" . | quote }}
  S3_BUCKET_RAW: "raw-telemetry-blobs"
  S3_BUCKET_CAPSULES: "capsule-samples"

  # Milvus configuration
  MILVUS_HOST: {{ include "slo-scout.milvusHost" . | quote }}
  MILVUS_PORT: "19530"
  MILVUS_COLLECTION: {{ .Values.backend.vectordb.collectionName | default "capsules" | quote }}

  # Kafka topics
  KAFKA_TOPIC_RAW_TELEMETRY: "raw-telemetry"
  KAFKA_TOPIC_CAPSULE_EVENTS: "capsule-events"
  KAFKA_TOPIC_CAPSULE_EMBEDDINGS: "capsule-embeddings"
  KAFKA_TOPIC_DLQ: "raw-telemetry-dlq"
  KAFKA_TOPIC_ANALYSIS_JOBS: "analysis-jobs"
