---
apiVersion: v1
kind: Secret
metadata:
  name: slo-scout-db-credentials
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ index .Values.secrets "slo-scout-db-credentials" "password" | default "changeme" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slo-scout-minio-credentials
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ index .Values.secrets "slo-scout-minio-credentials" "accessKey" | default "minioadmin" | quote }}
  secretKey: {{ index .Values.secrets "slo-scout-minio-credentials" "secretKey" | default "changeme" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slo-scout-jwt-secret
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretKey: {{ index .Values.secrets "slo-scout-jwt-secret" "secretKey" | default (randAlphaNum 32) | quote }}
---
{{- if eq .Values.backend.llm.provider "openai" }}
apiVersion: v1
kind: Secret
metadata:
  name: slo-scout-llm-credentials
  namespace: {{ include "slo-scout.namespace" . }}
  labels:
    {{- include "slo-scout.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ index .Values.secrets "slo-scout-llm-credentials" "apiKey" | required "LLM API key required for OpenAI provider" | quote }}
{{- end }}
